apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod

spec:
  containers:
  - name: nginx-container
    image: nginx

    env:
    - name: APP_ENV
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_ENV

    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: DB_HOST